paths:
  /users/{userId}:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: path
          name: userId
          required: false
          type: integer
          description: 'A small description about this'
        - in: query
          name: sort
          description: sort order
          required: true
          type: string
          enum: [asc, desc]
        - in: body
          description: The user to create.
          schema:
            $ref: '#/definitions/User'

      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

definitions:
  User:
    properties:
      id:
        type: string
      title:
        type: string
        example: Hello Hello
