paths:
  /users/{userId}:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: path
          name: userId
          required: false
          type: integer
          description: 'A small description about this'

      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

definitions:
  User:
    properties:
      id:
        type: string
