paths:
  /blogs:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200': # status code
          description: A `Array<Blogs>` array of user names
          schema:
            type: array
            items:
              $ref: '#/definitions/Blogs'

definitions:
  Blogs:
    properties:
      id:
        type: string
      user:
        type:
          $ref: '#/definitions/User'

schemes:
  - testOther
  - test2Other
